version: "3.0"
services:
  app:
    depends_on: 
      - db
    build: ./app
    ports:
      - "8050:8050"

  db:
    image: mysql:latest
    # build: ./database
    environment: 
      # MYSQL_HOST: 127.0.0.1
      # MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "33000:3306"
    # expose: :
    #   - 3306
    volumes:
    - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/init.sql"
    # command: ./tmp/database/init_user.sh
    