version: "3.0"
services:
  app:
    depends_on: 
      - db
    build: ./app_dockerfile
    ports:
      - "8050:8050"
    # networks:
    #   test:
    #     aliases:
    #       - mysql #Any container connected to test network can access this simply by using mysql as hostname  

  db:
    image: mysql:latest
    environment: 
      MYSQL_HOST: 127.0.0.1
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
    - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/depenses.sql"
  #   networks:
  #     test:
  #       aliases:
  #         - mysql #Any container connected to test network can access this simply by using mysql as hostname  

  # networks:
  #   test:
  #     external: true
