---
# User with root privileges that will install and launch the application
user_ansible: "user-ansible" 

recount_db_host: "localhost"
recount_db_port: 3306
recount_db_name: "recount"
recount_db_username: "recount-admin"
recount_db_password: "ShouldBeEncodedUsing_AnsibleVault"

recount_gunicorn_host: 0.0.0.0 # Can be changed to use a reverse proxy like Nginx
recount_gunicorn_port: 8080

recount_git_url: "https://github.com/Raiytak/Recount.git"
recount_version: "v0.3"

recount_folder: "/var/www/html/Recount"
recount_git_folder: "{{recount_folder}}/code"
recount_virtual_env: "{{recount_folder}}/virtual_env"
recount_virtual_env_python: "{{recount_virtual_env}}/bin/python"
recount_mysql_init: "{{recount_git_folder}}/db/sql/init.sql"

recount_working_folder: "/home/{{user_ansible}}/.recount"