

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `recount` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `recount`;


DROP TABLE IF EXISTS `expense`;
CREATE TABLE IF NOT EXISTS `expense` (
  `ID` int(11) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `date` date NOT NULL,
  `amount` float NOT NULL,
  `currency` VARCHAR(3) NOT NULL,
  `category` VARCHAR(75) DEFAULT NULL,
  `receiver` VARCHAR(50) DEFAULT NULL,
  `place` VARCHAR(50) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `payment_method` varchar(30) DEFAULT 'card',
  PRIMARY KEY (`username`, `ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


-- DROP TABLE IF EXISTS `reimbursement`;
-- CREATE TABLE IF NOT EXISTS `reimbursement` (
--   `username` VARCHAR(255) NOT NULL,
--   `ID` int(11) NOT NULL,
--   `ID_origin` int(11) NOT NULL,
--   `amount` float NOT NULL,
--   PRIMARY KEY (`username`, `ID`)
-- ) ENGINE=MyISAM DEFAULT CHARSET=latin1;


COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;


