---
- name: mysql installation
  ansible.builtin.apt:
    name: mysql-server,python3-mysqldb
    state: present

- name: start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

