FROM mysql:latest

# VOLUME ./database:/tmp/database

# ENV MYSQL_TCP_PORT='3306'
ENV MYSQL_ROOT_PASSWORD='root'
# ENV MYSQL_DATABASE='depenses'
# ENV MYSQL_USER='myuser'
# ENV MYSQL_PASSWORD='mypass'

# RUN mysqld --init-file="/tmp/database/init.sql"
# RUN ./tmp/database/init_user.sh


